# Generated by Django 5.2.6 on 2025-11-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='cat',
        ),
        migrations.AddField(
            model_name='client',
            name='car',
            field=models.CharField(blank=True, max_length=100, verbose_name='Автомобиль'),
        ),
    ]
