# Generated by Django 5.2.6 on 2025-11-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_client_cat_client_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='car',
        ),
        migrations.AddField(
            model_name='client',
            name='car_brand',
            field=models.CharField(blank=True, max_length=100, verbose_name='Марка автомобиля'),
        ),
        migrations.AddField(
            model_name='client',
            name='car_license_plate',
            field=models.CharField(blank=True, max_length=15, verbose_name='Госномер'),
        ),
        migrations.AddField(
            model_name='client',
            name='car_model',
            field=models.CharField(blank=True, max_length=100, verbose_name='Модель автомобиля'),
        ),
        migrations.AddField(
            model_name='client',
            name='car_vin',
            field=models.CharField(blank=True, max_length=17, verbose_name='VIN код'),
        ),
        migrations.AddField(
            model_name='client',
            name='car_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Год выпуска'),
        ),
    ]
