# Generated by Django 5.2.6 on 2025-11-04 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autoservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('location', models.CharField(max_length=255, verbose_name='Местоположение')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
                ('type_of_verificating', models.CharField(choices=[('basic', 'Базовая'), ('premium', 'Премиум'), ('verified', 'Верифицированный')], default='basic', max_length=20, verbose_name='Тип верификации')),
                ('cat_branch', models.CharField(max_length=100, verbose_name='Категория услуг')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
