# Generated by Django 5.2.6 on 2025-11-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoservice',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Прошел верификацию'),
        ),
        migrations.AddField(
            model_name='autoservice',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='autoservice',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='autoservice',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата верификации'),
        ),
    ]
